coverage:
  status:
    project:
      default:
        # basic
        target: auto
        threshold: 5%
ignore:
  - 'node_modules/'
  - 'src/base/utils/document-component.tsx'
  - 'src/base/test-polyfill.js'
  - 'src/index.tsx.js'
  - 'src/setupTests.js'
  - 'src/rmwc/**/*'
  - 'src/**/*.story.*'
  - 'src/**/*.spec.*'
  - 'src/**/readme*'
  - 'src/doc-utils*'
