name: NX Migrate Latest

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 4' # every friday at midnight

jobs:
  nx_migrate:
    name: NX Migrate
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.1
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
      - run: npm ci --ignore-scripts
      - name: NX Migrate
        uses: timonmasberg/nx-migration-gh-action@v1.1.12
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          base: 'master'
