name: RMWC Publish

on:
  pull_request:
    branches: [master]
    types: [closed]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          registry-url: 'https://registry.npmjs.org'
      - run: npm i react react-dom
      - run: npm ci
      - run: npm test
        env:
          CI: true
      - name: Codecov
        uses: codecov/codecov-action@v2
