name: RMWC Publish

# only trigger on pull request closed events
on:
  pull_request:
    branches: [master]
    types: [closed]

jobs:
  publish:
    runs-on: ubuntu-latest
    # this job will only run if the PR has been merged
    if: contains(github.head_ref, 'testpublish') && github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npx lerna exec -- npm publish --tag latest
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
