name: RMWC Release

on:
  pull_request:
    branches: [master]

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    if: contains(github.head_ref, 'release/')
    steps:
      - uses: actions/checkout@v2
      - name: Setup Git
        run: git fetch origin ${{ github.head_ref }} && git checkout ${{ github.head_ref }}
      - run: git config --global user.email "ci@rmwc.io"
      - run: git config --global user.name "RMWC CI"
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run release:patch
        if: contains(github.head_ref, '/patch')
      - run: npm run release:minor
        if: contains(github.head_ref, '/minor')
      - run: npm run release:major
        if: contains(github.head_ref, '/major')
